// Diff set of classes, functions, variables no longer defined on the script and global scope. (0.7.9-0.8.0).
module.exports = {
  "globals": {

    // Classes
    "EmbeddedEntity": "readonly",
    "Entity": "readonly",
    "EntityCollection": "readonly",
    "EULA": "readonly",
    "InstallPackage": "readonly",
    "PlayerConfig": "readonly",
    "SetupConfiguration": "readonly",
    "SetupConfigurationForm": "readonly",
    "UpdateNotes": "readonly",
    "UserManagement": "readonly",
    "WorldConfig": "readonly",
    "WorldSettingsStorage": "readonly",

    // Functions
    "_handleMouseWheelInputChange": "readonly",
    "clampNumber": "readonly",
    "loadFont": "readonly",
    "normalizeDegrees": "readonly",
    "normalizeRadians": "readonly",
    "roundDecimals": "readonly",
    "toDegrees": "readonly",
    "toRadians": "readonly",

    // Variables
    "ACTIVE_EFFECT_MODES": "readonly",
    "ASCII": "readonly",
    "AUDIO_FILE_EXTENSIONS": "readonly",
    "BASE_ENTITY_TYPE": "readonly",
    "CHAT_MESSAGE_TYPES": "readonly",
    "COMPENDIUM_ENTITY_TYPES": "readonly",
    "CORE_SUPPORTED_LANGUAGES": "readonly",
    "DEFAULT_NOTE_ICON": "readonly",
    "DEFAULT_TOKEN": "readonly",
    "DICE_ROLL_MODES": "readonly",
    "DRAWING_DEFAULT_VALUES": "readonly",
    "DRAWING_FILL_TYPES": "readonly",
    "DRAWING_TYPES": "readonly",
    "ENTITY_LINK_TYPES": "readonly",
    "ENTITY_PERMISSIONS": "readonly",
    "ENTITY_TYPES": "readonly",
    "EULA_VERSION": "readonly",
    "FOLDER_ENTITY_TYPES": "readonly",
    "FOLDER_MAX_DEPTH": "readonly",
    "FONTS": "readonly",
    "GRID_MIN_SIZE": "readonly",
    "GRID_TYPES": "readonly",
    "HTML_FILE_EXTENSIONS": "readonly",
    "IMAGE_FILE_EXTENSIONS": "readonly",
    "MACRO_SCOPES": "readonly",
    "MEDIA_MIME_TYPES": "readonly",
    "PACKAGE_AVAILABILITY_CODES": "readonly",
    "PASSWORD_SAFE_STRING": "readonly",
    "PLAYLIST_MODES": "readonly",
    "SOFTWARE_UPDATE_CHANNELS": "readonly",
    "SORT_INTEGER_DENSITY": "readonly",
    "SOURCE_TYPES": "readonly",
    "TABLE_RESULT_TYPES": "readonly",
    "TEXT_ANCHOR_POINTS": "readonly",
    "TOKEN_DISPLAY_MODES": "readonly",
    "TOKEN_DISPOSITIONS": "readonly",
    "USER_PERMISSIONS": "readonly",
    "USER_ROLE_NAMES": "readonly",
    "USER_ROLES": "readonly",
    "VIDEO_FILE_EXTENSIONS": "readonly",
    "VTT": "readonly",
    "WALL_DIRECTIONS": "readonly",
    "WALL_DOOR_STATES": "readonly",
    "WALL_DOOR_TYPES": "readonly",
    "WALL_MOVEMENT_TYPES": "readonly",
    "WALL_SENSE_TYPES": "readonly",
    "WEBSITE_URL": "readonly"
  }
}